### ISSUE TITLE
Doesnt work just keeps saying [97mZoom Join Meeting Not Found on[42mScreen

### ISSUE THREAD

**Issue by zer0mania** [UBISOFT-1/ShameOnYou#1]
help

**Comment by OttomanZ** [comment]
Sure I am here to help you, what version of the zoom client are you using and yes you can change the join-meeting icon by taking a new screenshot of the icon and replacing it

**Comment by OttomanZ** [comment]
you can also DM me on discord at OTTOMAN#5912 and you can video share and help you resolve that problem but probably it is just the icon that you can just update make sure to keep its name same
:)

**Comment by OttomanZ** [comment]
Here is a video show how to bypass it, I made it for you https://youtu.be/VQpo06cs3O4
If you are getting the error that join button is not found, then please log in to a zoom account and then if it still cannot do something then just give it a little help and once it is started it will do the thing
@rhizomacomp10

**Comment by OttomanZ** [comment]
Hope this solves it the image you are taking about, sometimes it does that, but give it a little help and it will do the rest and if still there are issues just replace all the images with the images of these steps on your own PC, and yes do not forget this is STRICTLY FOR EDUCATIONAL PURPOSES ONLY.
